In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_openml

In [47]:
data = fetch_openml(data_id=1597, as_frame=True)

X = data.data
y = data.target.astype(int)

In [48]:
X.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99

In [49]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int64

In [50]:
print("Shape(rows, attributes):",X.shape)
print("Columns: ", list(X.columns))
print()
print(y.value_counts())
print(f"{y.mean():.3%}")
print()
print("Missing Values:", X.isnull().sum().sum())
print("Duplicates:", X.duplicated().sum())

Shape(rows, attributes): (284807, 29)
Columns:  ['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount']

Class
0    284315
1       492
Name: count, dtype: int64
0.173%

Missing Values: 0
Duplicates: 9144

In [51]:
from sklearn.model_selection import train_test_split
X_train, X_rem, y_train, y_rem = train_test_split(X, y, test_size=0.4, stratify=y, random_state=2)

In [52]:
X_val, X_test, y_val, y_test = train_test_split(X_rem, y_rem, test_size=0.5, stratify=y_rem, random_state=2)

In [53]:
for name, X_sets, y_sets in [("Training", X_train, y_train), ("Validation", X_val, y_val), ("Testing", X_test, y_test)]:
  print(f"{name}: {X_sets.shape[0]} rows, {y_sets.sum()} frauds, ({y_sets.mean():.5%})")

Training: 170884 rows, 295 frauds, (0.17263%)
Validation: 56961 rows, 98 frauds, (0.17205%)
Testing: 56962 rows, 99 frauds, (0.17380%)

In [62]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_trainScaled = scaler.fit_transform(X_train)
X_valScaled = scaler.transform(X_val)
X_testScaled = scaler.transform(X_test)

print(X_trainScaled[:,0].mean(), X_trainScaled[:,0].std())
print(X_valScaled[:,0].mean(), X_valScaled[:,0].std())
print(X_trainScaled.shape, X_valScaled.shape, X_testScaled.shape)

1.3721536410713294e-18 0.9999999999999999
-0.0011893840816954169 0.9906599835554472
(170884, 29) (56961, 29) (56962, 29)